/**
 * Importe la documentation des packs depuis le dépôt Unity privé.
 *
 * Les `README.md` et `CHANGELOG.md` des packs sont déjà écrits en anglais et
 * font foi (règle du CLAUDE.md du dépôt Unity). Les recopier à la main ici,
 * c'est garantir qu'ils divergeront. Ce script en fait un produit dérivé :
 * les pages générées portent `editUrl: false` et un avertissement, pour que
 * personne ne les corrige au mauvais endroit.
 *
 * Usage :
 *   npm run sync
 *   FOS_UNITY_PROJECT="D:/chemin/vers/le/projet" npm run sync
 */

import {
	readFileSync,
	writeFileSync,
	mkdirSync,
	existsSync,
	readdirSync,
} from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const siteRoot = resolve(here, '..');

// Par défaut, le projet Unity est le dossier frère. Surchargeable par variable
// d'environnement pour ne pas figer un chemin de machine dans un dépôt public.
const unityRoot = resolve(
	process.env.FOS_UNITY_PROJECT ??
		join(siteRoot, '..', 'French Oasis Studio Tech')
);

const packs = JSON.parse(
	readFileSync(join(siteRoot, 'src/data/packs.json'), 'utf8')
);
const byId = new Map(packs.map((p) => [p.id, p]));

const DOCS = join(siteRoot, 'src/content/docs');
const PUBLIC = join(siteRoot, 'public');
const SITE = 'https://essentials.frenchoasis.studio';
const NL = String.fromCharCode(10);

/** Langues dans lesquelles un README peut exister, en plus de l'anglais. */
const TRANSLATED = ['fr', 'es', 'de'];
const siteMeta = JSON.parse(
	readFileSync(join(siteRoot, 'src/data/site.json'), 'utf8')
);
/** Corps des README, conserve pour alimenter llms-full.txt. */
const fullDocs = new Map();
const GENERATED_NOTE =
	'<!-- Generated by scripts/sync-packs.mjs from the pack sources. Do not edit here. -->';

/** Retire le BOM que certains README portent encore. */
function stripBom(text) {
	return text.charCodeAt(0) === 0xfeff ? text.slice(1) : text;
}

/** Retire le premier titre H1 : il devient le `title` du frontmatter. */
function stripLeadingH1(body) {
	const lines = body.split(/\r?\n/);
	const first = lines.findIndex((l) => l.trim() !== '');
	if (first !== -1 && /^#\s+/.test(lines[first])) {
		lines.splice(first, 1);
	}
	return lines.join('\n').replace(/^\s*\n+/, '');
}

/** Réécrit les liens relatifs entre fichiers du pack vers les routes du site. */
function rewriteLinks(body, pack, lang = 'en') {
	const prefix = lang === 'en' ? '' : `/${lang}`;
	return body
		.replace(/\]\(\.?\/?CHANGELOG\.md\)/g, `](${prefix}/changelogs/${pack.id}/)`)
		.replace(/\]\(\.?\/?README\.md\)/g, `](${prefix}/${pack.docsSlug}/)`);
}

/**
 * Bandeau de version en tête de page.
 *
 * Le H1 du README, qui portait la version, est retiré au profit du frontmatter.
 * Sans ce bandeau, la page ne dirait plus quelle version elle documente — et un
 * décalage entre le site et le pack passerait inaperçu, ce qui est arrivé le
 * 20/08/2026 avec le Core et Tablet System.
 */
const BANNER = {
	en: { version: 'Version', core: 'requires FOS Essentials Core', later: 'or later', also: 'also requires' },
	fr: { version: 'Version', core: 'exige FOS Essentials Core', later: 'ou plus récent', also: 'exige aussi' },
	es: { version: 'Versión', core: 'requiere FOS Essentials Core', later: 'o posterior', also: 'también requiere' },
	de: { version: 'Version', core: 'benötigt FOS Essentials Core', later: 'oder neuer', also: 'benötigt außerdem' },
};

function versionBanner(pack, lang = 'en') {
	const t = BANNER[lang] ?? BANNER.en;
	const parts = [`**${t.version} ${pack.version}**`];
	if (pack.minimumCore) {
		parts.push(`${t.core} ${pack.minimumCore} ${t.later}`);
	}
	if (pack.requires.length) {
		const deps = pack.requires
			.map((id) => {
				const dep = byId.get(id);
				return dep ? `${dep.name} ${dep.version}` : id;
			})
			.join(', ');
		parts.push(`${t.also} ${deps}`);
	}
	return `${parts.join(' · ')}\n`;
}

function emit(targetPath, frontmatter, body) {
	mkdirSync(dirname(targetPath), { recursive: true });
	const head = Object.entries(frontmatter)
		.map(([k, v]) => `${k}: ${v}`)
		.join('\n');
	writeFileSync(targetPath, `---\n${head}\n---\n\n${GENERATED_NOTE}\n\n${body}\n`, 'utf8');
}

/**
 * Échappe une valeur de frontmatter. Les règles de citation JSON sont un
 * sous-ensemble valide du YAML entre guillemets, ce qui évite un échappement
 * maison.
 */
function yamlString(value) {
	return JSON.stringify(String(value));
}

let written = 0;
const missing = [];

for (const pack of packs) {
	const packDir = join(unityRoot, pack.sourcePath);

	// --- README -> /packs/<id>, et /<lang>/packs/<id> si traduit ---
	//
	// Le README anglais fait foi ; un `README.fr.md` pose a cote de lui produit
	// la page francaise. La traduction vit donc dans le depot Unity, au meme
	// endroit que sa source, et part avec le pack chez l'acheteur — plutot que
	// d'etre recopiee ici, ou elle divergerait au premier changement.
	const readmePath = join(packDir, 'README.md');
	if (existsSync(readmePath)) {
		for (const lang of ['en', ...TRANSLATED]) {
			const file =
				lang === 'en' ? readmePath : join(packDir, `README.${lang}.md`);
			if (!existsSync(file)) continue;

			const body = rewriteLinks(
				stripLeadingH1(stripBom(readFileSync(file, 'utf8'))),
				pack,
				lang
			);

			emit(
				lang === 'en'
					? join(DOCS, `${pack.docsSlug}.md`)
					: join(DOCS, lang, `${pack.docsSlug}.md`),
				{
					title: yamlString(pack.name),
					description: yamlString(
						pack.description[lang] ?? pack.description.en
					),
					editUrl: 'false',
					sidebar: `\n  order: ${pack.order}`,
				},
				`${versionBanner(pack, lang)}\n${body}`
			);

			if (lang === 'en') fullDocs.set(pack.id, body);
			written++;
		}
	} else {
		missing.push(`${pack.id}: README.md`);
	}

	// --- CHANGELOG -> /changelogs/<id> ---
	const changelogPath = join(packDir, 'CHANGELOG.md');
	if (existsSync(changelogPath)) {
		const body = rewriteLinks(
			stripLeadingH1(stripBom(readFileSync(changelogPath, 'utf8'))),
			pack
		);
		emit(
			join(DOCS, `changelogs/${pack.id}.md`),
			{
				title: yamlString(`${pack.shortName} — Changelog`),
				description: yamlString(`Version history of ${pack.name}.`),
				editUrl: 'false',
				sidebar: `\n  order: ${pack.order}`,
			},
			body
		);
		written++;
	} else {
		missing.push(`${pack.id}: CHANGELOG.md`);
	}
}

// --- llms.txt -------------------------------------------------------
//
// Convention emergente : un resume du site en Markdown, a la racine, pour les
// agents qui lisent une page plutot que de la parcourir. `llms.txt` donne la
// carte, `llms-full.txt` donne tout le texte d'un seul tenant.

const lines = [
	'# FOS Essentials',
	'',
	'> Unity tools for VRChat worlds, built on UdonSharp by French Oasis Studio.',
	'> Every pack requires FOS Essentials Core, which is free.',
	'',
	`Unity ${siteMeta.unity} - VRChat SDK Worlds ${siteMeta.vrchatSdk} - Built-in render pipeline.`,
	'',
	'## Packs',
	'',
];

for (const pack of packs) {
	const price = pack.edition === 'free' ? 'free' : 'paid';
	lines.push(
		`- [${pack.name}](${SITE}/${pack.docsSlug}/): ${pack.description.en} Version ${pack.version}, ${price}.`
	);
}

lines.push('', '## Guides', '');
lines.push(`- [All packs](${SITE}/catalog/): the full catalogue, free and paid.`);
lines.push(`- [Installation](${SITE}/start/installation/): requirements and setup.`);
lines.push(
	`- [Compatibility](${SITE}/start/compatibility/): which pack needs which Core version.`
);
lines.push(`- [FAQ](${SITE}/faq/): Quest, requirements, dependencies, updating.`);

// Les guides sont lus sur le disque plutot que listes a la main : une page
// ajoutee et oubliee ici disparaitrait de la carte donnee aux agents.
const guidesDir = join(DOCS, 'guides');
if (existsSync(guidesDir)) {
	for (const file of readdirSync(guidesDir).sort()) {
		if (!file.endsWith('.md') && !file.endsWith('.mdx')) continue;
		const raw = readFileSync(join(guidesDir, file), 'utf8');
		const title = /^title:\s*"?(.+?)"?\s*$/m.exec(raw)?.[1] ?? file;
		const description = /^description:\s*"?(.+?)"?\s*$/m.exec(raw)?.[1] ?? '';
		const slug = file.replace(/\.mdx?$/, '');
		lines.push(`- [${title}](${SITE}/guides/${slug}/): ${description}`);
	}
}

lines.push('');

writeFileSync(join(PUBLIC, 'llms.txt'), lines.join(NL), 'utf8');

const full = [lines.join(NL), ''];
for (const pack of packs) {
	const doc = fullDocs.get(pack.id);
	if (!doc) continue;
	full.push(`# ${pack.name} ${pack.version}`, '', doc, '');
}
writeFileSync(join(PUBLIC, 'llms-full.txt'), full.join(NL), 'utf8');

console.log('sync-packs: llms.txt and llms-full.txt written to public/');

console.log(`sync-packs: ${written} page(s) written from ${unityRoot}`);

if (missing.length) {
	// Un pack sans doc n'est pas une erreur bloquante — il est peut-être en
	// cours d'écriture — mais il ne doit jamais passer inaperçu.
	console.warn(`sync-packs: ${missing.length} source(s) missing:`);
	for (const item of missing) console.warn(`  - ${item}`);
}

if (written === 0) {
	console.error(
		`sync-packs: nothing found. Is FOS_UNITY_PROJECT correct? Tried: ${unityRoot}`
	);
	process.exit(1);
}
