/**
 * Importe la documentation des packs depuis le dépôt Unity privé.
 *
 * Les `README.md` et `CHANGELOG.md` des packs sont déjà écrits en anglais et
 * font foi (règle du CLAUDE.md du dépôt Unity). Les recopier à la main ici,
 * c'est garantir qu'ils divergeront. Ce script en fait un produit dérivé :
 * les pages générées portent `editUrl: false` et un avertissement, pour que
 * personne ne les corrige au mauvais endroit.
 *
 * Usage :
 *   npm run sync
 *   FOS_UNITY_PROJECT="D:/chemin/vers/le/projet" npm run sync
 */

import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const siteRoot = resolve(here, '..');

// Par défaut, le projet Unity est le dossier frère. Surchargeable par variable
// d'environnement pour ne pas figer un chemin de machine dans un dépôt public.
const unityRoot = resolve(
	process.env.FOS_UNITY_PROJECT ??
		join(siteRoot, '..', 'French Oasis Studio Tech')
);

const packs = JSON.parse(
	readFileSync(join(siteRoot, 'src/data/packs.json'), 'utf8')
);

const DOCS = join(siteRoot, 'src/content/docs');
const GENERATED_NOTE =
	'<!-- Generated by scripts/sync-packs.mjs from the pack sources. Do not edit here. -->';

/** Retire le BOM que certains README portent encore. */
function stripBom(text) {
	return text.charCodeAt(0) === 0xfeff ? text.slice(1) : text;
}

/** Retire le premier titre H1 : il devient le `title` du frontmatter. */
function stripLeadingH1(body) {
	const lines = body.split(/\r?\n/);
	const first = lines.findIndex((l) => l.trim() !== '');
	if (first !== -1 && /^#\s+/.test(lines[first])) {
		lines.splice(first, 1);
	}
	return lines.join('\n').replace(/^\s*\n+/, '');
}

/** Réécrit les liens relatifs entre fichiers du pack vers les routes du site. */
function rewriteLinks(body, pack) {
	return body
		.replace(/\]\(\.?\/?CHANGELOG\.md\)/g, `](/changelogs/${pack.id}/)`)
		.replace(/\]\(\.?\/?README\.md\)/g, `](/${pack.docsSlug}/)`);
}

/** Échappe une valeur de frontmatter YAML en chaîne entre guillemets. */
function yamlString(value) {
	return JSON.stringify(String(value));
}

function emit(targetPath, frontmatter, body) {
	mkdirSync(dirname(targetPath), { recursive: true });
	const head = Object.entries(frontmatter)
		.map(([k, v]) => `${k}: ${v}`)
		.join('\n');
	writeFileSync(targetPath, `---\n${head}\n---\n\n${GENERATED_NOTE}\n\n${body}\n`, 'utf8');
}

let written = 0;
const missing = [];

for (const pack of packs) {
	const packDir = join(unityRoot, pack.sourcePath);

	// --- README -> /packs/<id> ---
	const readmePath = join(packDir, 'README.md');
	if (existsSync(readmePath)) {
		const body = rewriteLinks(
			stripLeadingH1(stripBom(readFileSync(readmePath, 'utf8'))),
			pack
		);
		emit(
			join(DOCS, `${pack.docsSlug}.md`),
			{
				title: yamlString(pack.name),
				description: yamlString(pack.description.en),
				editUrl: 'false',
				sidebar: `\n  order: ${pack.order}`,
			},
			body
		);
		written++;
	} else {
		missing.push(`${pack.id}: README.md`);
	}

	// --- CHANGELOG -> /changelogs/<id> ---
	const changelogPath = join(packDir, 'CHANGELOG.md');
	if (existsSync(changelogPath)) {
		const body = rewriteLinks(
			stripLeadingH1(stripBom(readFileSync(changelogPath, 'utf8'))),
			pack
		);
		emit(
			join(DOCS, `changelogs/${pack.id}.md`),
			{
				title: yamlString(`${pack.shortName} — Changelog`),
				description: yamlString(`Version history of ${pack.name}.`),
				editUrl: 'false',
				sidebar: `\n  order: ${pack.order}`,
			},
			body
		);
		written++;
	} else {
		missing.push(`${pack.id}: CHANGELOG.md`);
	}
}

console.log(`sync-packs: ${written} page(s) written from ${unityRoot}`);

if (missing.length) {
	// Un pack sans doc n'est pas une erreur bloquante — il est peut-être en
	// cours d'écriture — mais il ne doit jamais passer inaperçu.
	console.warn(`sync-packs: ${missing.length} source(s) missing:`);
	for (const item of missing) console.warn(`  - ${item}`);
}

if (written === 0) {
	console.error(
		`sync-packs: nothing found. Is FOS_UNITY_PROJECT correct? Tried: ${unityRoot}`
	);
	process.exit(1);
}
